export const smCPSpacing = 3
export const lgCPButtHeadSpacing = 1
export const smCPButtHeadSpacing = 3
export const cpSpacing = 1
export const wording = {
	FRAMES: 'Frames',
	HEIGHT: 'Height',
	KNOCKDOWN: 'Knockdown',
	LAUNCH: 'Launch',
	RAGE: 'Rage',
	SAFETY: 'Safety',
	SITUATIONAL: 'Situational',
	STRINGS: 'Strings',
	RANGE: 'Range',
	SPECIFIC: 'Specific',
	'START & FINISH': 'Start & Finish',
	NORMAL: 'Normal',
	COUNTER: 'Counter',
	'RAGE ART': 'Rage Art',
	'RAGE DRIVE': 'Rage Drive',
	SAFE: 'Safe',
	UNSAFE: 'Unsafe',
	'+ON BLOCK': '+ On Block',
	'POWER CRUSH': 'Power Crush',
	'WALL BOUNCE': 'Wall Bounce',
	HOMING: 'Homing',
	SINGLE: 'Single',
	DOUBLE: 'Double',
	TRIPPLE: 'Tripple',
}

export const cpButtons = {
	FRAMES: ['RANGE', 'SPECIFIC'],
	HEIGHT: ['SPECIFIC', 'START & FINISH'],
	KNOCKDOWN: ['NORMAL', 'COUNTER'],
	LAUNCH: ['NORMAL', 'COUNTER'],
	RAGE: ['RAGE ART', 'RAGE DRIVE'],
	SAFETY: ['SAFE', 'UNSAFE'],
	SITUATIONAL: ['+ON BLOCK', 'POWER CRUSH', 'WALL BOUNCE', 'HOMING'],
	STRINGS: ['SINGLE', 'DOUBLE', 'TRIPPLE'],
}
export const cpInputs = {
	framesSpecific: ['0-13', '13-17', '17-20', '20-'],
	height: ['H', 'M', 'L'],
}
export const buttonColors = {
	buttonBackground: {
		buttonFocusBackground: 'orange',
		buttonBlurBackground: 'white',
	},
}
export const charactersArr = [
	'Akuma',
	'Alisa',
	'Anna',
	'Armor King',
	'Asuka',
	'Bob',
	'Bryan',
	'Claudio',
	'Devil Jin',
	'Dragunov',
	'Eddy',
	'Eliza',
	'Fahkumram',
	'Feng',
	'Ganryu',
	'Geese',
	'Gigas',
	'Heihachi',
	'Hwoarang',
	'Jack',
	'Jin',
	'Josie',
	'Julia',
	'Katarina',
	'Kazumi',
	'Kazuya',
	'King',
	'Kuma',
	'Lars',
	'Law',
	'Lee',
	'Lei',
	'Leo',
	'Leroy',
	'Lili',
	'LuckyChoe',
	'Marduk',
	'MasterRaven',
	'Miguel',
	'Negan',
	'Nina',
	'Noctis',
	'Paul',
	'Shaheen',
	'Steve',
	'Xiaoyu',
	'Yoshimitsu',
	'Zafina',
]
