import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Introduction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tekkenIcon.ico" />
      </Head>

      <Link href="/main">
        <button>Control Panel 1</button>
      </Link>
    </div>
  )
}
