import { makeStyles } from '@material-ui/core/styles'
import React, { useState } from 'react'
import Head from 'next/head'
import Grid from '@material-ui/core/Grid'
import cpStyles from '../styles/ControlPanel.module.css'
import homeStyles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

import Stepper from '@material-ui/core/Stepper'
import Step from '@material-ui/core/Step'
import StepLabel from '@material-ui/core/StepLabel'
import Button from '@material-ui/core/Button'
import Typography from '@material-ui/core/Typography'
import Paper from '@material-ui/core/Paper'
import tekkennetLogo from '../public/images/tekkennetLogo.svg'

// function getStepContent(stepIndex) {
//   switch (stepIndex) {
//     case 0:
//       return 'Welcome'
//     case 1:
//       return 'Instructions'
//     case 2:
//       return 'This is the bit I really care about!'
//     default:
//       return 'Unknown stepIndex'
//   }
// }

export default function Home({ state }) {
  const [activeStep, setActiveStep] = useState(0)
  const { isSmallScreen } = state
  const steps = getSteps()

  const handleNext = () => {
    if (activeStep < 2) setActiveStep((prevActiveStep) => prevActiveStep + 1)
  }

  const handleBack = () => {
    setActiveStep((prevActiveStep) => prevActiveStep - 1)
  }

  const handleReset = () => {
    setActiveStep(0)
  }

  function getSteps() {
    return ['Welcome', 'Purpose', 'Instructions']
  }

  const useStyles = makeStyles((theme) => ({
    root: {
      width: '100%',
    },
    backButton: {
      marginRight: theme.spacing(1),
    },
    instructions: {
      marginTop: theme.spacing(1),
      marginBottom: theme.spacing(1),
    },
  }))

  const classes = useStyles()

  const TekkenetLogo = () => {
    return (
      <Image
        width="400"
        height="50"
        // className={styles.tekkennet_logo}
        src={tekkennetLogo}></Image>
    )
  }
  console.log(activeStep)
  return (
    <Grid
      container
      direction="column"
      justifyContent="center"
      alignItems="center"
      className={homeStyles.intro_container}>
      <Head>
        <title>Introduction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tekkenIcon.ico" />
      </Head>
      <Image
        className={homeStyles.background}
        src="/images/backgroundSVG.svg"
        layout="fill"
        objectFit="cover"
        quality={100}
      />
      {/* <Link href="/main">
        <button>Control Panel 1</button>
      </Link> */}
      <Grid
        container
        direction="column"
        justifyContent="center"
        alignItems="center">
        <Grid item>
          <TekkenetLogo />
        </Grid>
        <Grid item>
          <Grid
            container
            direction="column"
            className={classes.root}
            spacing={2}
            alignItems="center">
            <Grid item>
              <Paper
                style={{
                  width: isSmallScreen ? '300px' : '800px',
                  height: isSmallScreen ? '550px' : '80vh',
                  minHeight: '700px',
                }}>
                <Grid container direction="column" alignItems="center">
                  <Grid item xs={12} style={{ width: '100%' }}>
                    <Stepper activeStep={activeStep} alternativeLabel>
                      {steps.map((label) => (
                        <Step key={label}>
                          <StepLabel>{label}</StepLabel>
                        </Step>
                      ))}
                    </Stepper>
                  </Grid>
                </Grid>
              </Paper>
            </Grid>
            <Grid item>
              <Grid item>
                <Grid container>
                  <Grid item>
                    <Button
                      disabled={activeStep === 0}
                      onClick={handleBack}
                      className={classes.backButton}>
                      Back
                    </Button>
                  </Grid>
                  <Grid item>
                    <Link href={activeStep === 2 ? '/main' : ''}>
                      <Button
                        variant="contained"
                        color="primary"
                        onClick={handleNext}>
                        {activeStep === 2 ? 'Go To App' : 'Next'}
                      </Button>
                    </Link>
                  </Grid>
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </Grid>
  )
}
